version: "3.5"
services:
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./:/opt/keycloak/data/
    # ports:
    #   - 8080:8080
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"